language: android
jdk: oraclejdk8
node_js: node
install: yarn
android:
  components:
    - tools
    - platform-tools
    - android-26
    - extra-google-m2repository
    - extra-google-google-play-services
script: 
  - cd ./android
  - chmod +x ./gradlew 
  - ./gradlew build connectedCheck