- language: android
  jdk: oraclejdk8
  android:
    components:
      - tools
      - android-25
      - build-tools-27.0.3
    before_script:
      - cd android
    script: ./gradlew build connectedCheck